(require 'cljs.build.api)
(require 'cljs.repl)
(require 'cljs.repl.browser)

(cljs.build.api/build "src"
                      {
                       ;; The program entry point. `goog` loads and executes this module / namespace.
                       ;; By specifying the entry point, I *need not* specify it as the text of the last
                       ;; `script` tag.
                       :main 'cljs-first-project.core 
                       ;; The path of the JavaScript file to output.
                       :output-to "out/main.js"
                       ;; Present verbose output during compilation
                       :verbose true}) 

(cljs.repl/repl
 ;; We evaluate "on the browser."
 (cljs.repl.browser/repl-env)
 ;; Watch "src" for changes
 :watch "src"
 ;; Where to look for artifacts generated by build.
 ;; Remember that output of compilation goes into `out/watch.log`.
 :output-dir "out")

